#pragma config(Sensor, dgtl2,  fireRelay,      sensorDigitalOut)
#pragma config(Motor,  port2,           rightDriveMotor, tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port3,           leftDriveMotor, tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port4,           armMotor,      tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

const int DB_THRESH = 10; // radius

int FIRE_RELAY_DELAY = 100; // milliseconds
const int FIRE_CONFIRM_DELAY = 1000; // milliseconds
bool firingStarted = false; // true if fireBtn pressed, routine started

float squareInput(float input) {
	return input * abs(input) / 127;
}

float deadband(float input) {
	return (abs(input) >= DB_THRESH) ? input : 0.0;
}

void fireBeanBag(int fireDelay) {
  SensorValue[fireRelay] = 1
  ;
  sleep(fireDelay);
  SensorValue[fireRelay] = 0;
  firingStarted = false;
}

task main()
{
	while (true) {
	  /**
		 * Open loop arcade drive.
		 */
		float throttle = vexRT[Ch3];
		float turn = vexRT[Ch1];
		int slowturn = vexRT[Btn6U];

		throttle = deadband(throttle);
		turn = deadband(turn);

		if (slowturn == 1) {
			turn /= 2;
		}

		throttle = squareInput(throttle);
		turn = squareInput(turn);

		if (firingStarted == false) {
			motor[rightDriveMotor] = throttle + turn;
			motor[leftDriveMotor] = throttle - turn;
		}
		else {
			motor[rightDriveMotor] = 0.0;
			motor[leftDriveMotor] = 0.0;
		}

		/**
		 * Open loop arm control.
		 */
		int upBtn = vexRT[Btn5U]; // boolean, 0 or 1
		int downBtn = vexRT[Btn5D]; // boolean, 0 or 1

		if (upBtn == 1) {
			motor[armMotor] = 63.5;
		}
		else if (downBtn == 1) {
			motor[armMotor] = -63.5;
		}
		else {
			motor[armMotor] = 0.0;
		}

		/**
		 * Cannon control.
		 */
		int fireBtn = vexRT[Btn6D];


		if (vexRT[Btn7U] == 1) { FIRE_RELAY_DELAY = 100; }
		if (vexRT[Btn7R] == 1) { FIRE_RELAY_DELAY = 200; }
		if (vexRT[Btn7D] == 1) { FIRE_RELAY_DELAY = 300; }
		if (vexRT[Btn7L] == 1) { FIRE_RELAY_DELAY = 400; }
		if (vexRT[Btn8U] == 1) { FIRE_RELAY_DELAY = 500; }
		if (vexRT[Btn8R] == 1) { FIRE_RELAY_DELAY = 600; }
		if (vexRT[Btn8D] == 1) { FIRE_RELAY_DELAY = 700; }
		if (vexRT[Btn8L] == 1) { FIRE_RELAY_DELAY = 800; }

		if (fireBtn == 1 && firingStarted == false) {
			firingStarted = true;
			clearTimer(T1);
		}
		else if (fireBtn == 0 && firingStarted == true) {
			firingStarted = false;
		}
		else if (firingStarted == true && time1[T1] >= FIRE_CONFIRM_DELAY) {
			fireBeanBag(FIRE_RELAY_DELAY);
		}
	}
}
